# @package _global_

project: "train_sera"
run_name: h-sera_h_as_scale_1
run_version: vx_${run_name}
ckpt_path: last

module:
    super_resolution_model:
        scale: 1

datamodule:
    instance:
        batch_size: 8
    dataset:
        patch_size_input: 32
        patch_size_target: 32
        resolution_target: 10
        get_targets:
            targets_path: ${data_dir}/open_canopy/

