# @package _global_

defaults:
    - override /module/super_resolution_model: null
    - override /module/regression_model: unet
    - override /datamodule/dataset/get_inputs: s1_s2_composites
    - override /callbacks/image_type: s1_s2_composites

project: "train_sera"
run_name: h-unet_boosted_as
run_version: vx_${run_name}
data_dir: data/
ckpt_path: last

module:
    instance:
        super_resolution_model: null
    regression_model:
        encoder_widths: [100, 200, 400, 800, 1600]
        decoder_widths: [100, 200, 400, 800]

datamodule:
    instance:
        batch_size: 8
    dataset:
        gdf_path: ${data_dir}/sentinel/composites/height_map/gdf_height_map_composites.geojson
        patch_size_input: 128
        patch_size_target: 128
        resolution_input: 2.5
        get_targets:
            targets_path: ${data_dir}/open_canopy/


